[book]
title = "DQMJ1 ROM Editor"
authors = ["ExcaliburZero"]
language = "en"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["./mermaid.min.js", "./mermaid-init.js"]
